#!/bin/sh
#Le script se lance de la manière suivante (en sudoer dans le dossier courant):
#    ./osmo-all (start|stop|status|enable|disable)
#Il lance la nouvelle version de osmo-nitb avec osmo-bsc osmo-msc etc ...
cmd="${1:-status}"
set -ex
systemctl $cmd osmo-hlr osmo-msc osmo-mgw osmo-ggsn osmo-sgsn osmo-stp osmo-bsc osmo-sip-connector

